version: 2

updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "qitianshi"
      - "anweiteck"
    reviewers:
      - "qitianshi"
      - "anweiteck"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "qitianshi"
      - "anweiteck"
    reviewers:
      - "qitianshi"
      - "anweiteck"
