name: Analysis

on:
  workflow_dispatch:
    inputs:
      command:
        description: Command
        required: true
      date:
        description: Date
        required: true
      options:
        description: Options
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - uses: actions/cache@v3.0.2
      id: cache-venv
      with:
        path: ./venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Create Python venv and install dependencies
      run: python3 -m venv ./venv && . ./venv/bin/activate && pip install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Run analysis package
      run: >
        . ./venv/bin/activate && python3 -m analysis ${{ github.event.inputs.command }} ${{ github.event.inputs.date }} ${{ github.event.inputs.options }}

    - name: Commit, push, and create pull request
      uses: peter-evans/create-pull-request@v4.0.1
      with:
        branch: process-result
        branch-suffix: timestamp
        commit-message: 'Process results for ${{ github.event.inputs.date }}'
        committer: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
        author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
        base: main
        title: Process results for ${{ github.event.inputs.date }}
        reviewers: qitianshi, anweiteck
        assignees: qitianshi, anweiteck
