name: Process result

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Result date (YYYY-MM-DD_hhmm)'
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - uses: actions/cache@v2
      id: cache-venv
      with:
        path: ./venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Create Python venv and install dependencies
      run: python3 -m venv ./venv && . ./venv/bin/activate &&
           pip install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Run analysis package
      run: . ./venv/bin/activate && python3 -m analysis ${{ github.event.inputs.date }}

    - name: Commit, push, and create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: process-result-${{ github.event.inputs.date }}
        commit-message: 'Process result from ${{ github.event.inputs.date }}'
        committer: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
        author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
        base: main
        title: Processed results from ${{ github.event.inputs.date }}
        reviewers: qitianshi, anweiteck
        assignees: qitianshi, anweiteck
