name: Pylint

on:
  push:
    paths:
      'analysis/**'
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - uses: actions/cache@v3.2.3
      id: cache-venv
      with:
        path: ./venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Create Python venv and install dependencies
      run: python3 -m venv ./venv && . ./venv/bin/activate &&
           pip install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Analysing with pylint
      # Runs Pylint, disables refactor (R) messages and TODO/FIXME warnings (W0511)
      run: |
        . ./venv/bin/activate && pylint analysis --disable=R --disable=W0511
