name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - uses: actions/cache@v2
      id: cache-venv
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - run: python3 -m venv ./venv && . ./venv/bin/activate &&
           pip install -r requirements.txt && pip install pylint
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Analysing the code with pylint
      # Runs Pylint, disables refactor (R) messages and TODO/FIXME warnings (W0511)
      run: |
        ./venv/bin/activate && pylint analysis --disable=R --disable=W0511
